import { Inter } from "next/font/google";
import { Sanchez } from "next/font/google";
import "./globals.css";
import Footer from "./_components/Footer";

const inter = Inter({ subsets: ["latin"] });
const sanchez = Sanchez({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sanchez.className} custom-bg`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
