import { Inter } from "next/font/google";
import { Sanchez } from "next/font/google";
import "./globals.css";
import Footer from "./_components/Footer";

const inter = Inter({ subsets: ["latin"] });
const sanchez = Sanchez({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Tharam-Thiran Green Energy Flow Pvt Ltd",
  description: "Generated by create next app",
  keywords: "Renewable Energy, Energy Storage, Green Energy, Solar Energy, Tharam-Thiran Green Energy Flow Pvt Ltd, Tharam-Thiran, Tharam Thiran, Tharam, Thiran, Green Energy Flow, Green Energy Flow Pvt Ltd",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sanchez.className} custom-bg`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
